file_format: "1"
id: lily58_enc
name: Lily58_enc
type: shield
url: https://github.com/orvisevans/Lily58-Glow-Enc
requires: [nrfmicro/nrf52840]
features:
  - keys
  - encoder
siblings:
  - lily5_enc_left
  - lily5_enc_right
